<template>
    <div class="loadingio-spinner-eclipse-yrwf9w06mja"><div class="ldio-95lm66o02e">
<div></div>
</div></div>
</template>

<style>

@keyframes ldio-95lm66o02e {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-95lm66o02e div {
  position: absolute;
  animation: ldio-95lm66o02e 1s linear infinite;
  width: 160px;
  height: 160px;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #93dbe9;
  transform-origin: 80px 82px;
}
.loadingio-spinner-eclipse-yrwf9w06mja {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-95lm66o02e {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-95lm66o02e div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
